/// Workspace build — coordinates compiler-core, compiler-cli and language-server.
///
///   zig build          → builds botopink + botopink-lsp
///   zig build test     → runs every compiler-core test
///   zig build test -Dtest-filter=<substr> → runs only matching tests
///   zig build run      → builds and runs the botopink CLI
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // ── std prelude ───────────────────────────────────────────────────────────

    const std_prelude = b.addModule("std_prelude", .{
        .root_source_file = b.path("modules/compiler-core/src/comptime/stdlib/prelude.zig"),
        .target = target,
    });

    // Core controller files flattened into the global type env. These are NOT
    // importable "std" packages — `prelude.zig` embeds them by name, so they are
    // anonymous imports on the std_prelude module.
    const std_core_files = [_][]const u8{
        "primitives.d.bp",
        "builtins.d.bp",
    };
    for (std_core_files) |f| {
        std_prelude.addAnonymousImport(f, .{
            .root_source_file = b.path(b.fmt("libs/std/src/{s}", .{f})),
        });
    }

    // "std" package modules — importable via `import {…} from "std"`. This list
    // is the ONLY place a std module is wired: compiler-core discovers them
    // generically through the generated `std_pkg` table below, so adding a module
    // never touches `modules/compiler-core/src/**`. Adding a module is: drop
    // `libs/std/src/<name>.bp` + add `"<name>.bp"` here. (Application-level libs
    // like `erika` are NOT std — they ship under `libs/<name>/` and load through
    // the generic `from "<lib>"` loader, never this table.)
    const std_pkg_files = [_][]const u8{
        "order.bp",
        "dict.bp",
        "sets.bp",
        "string_builder.bp",
        "queue.bp",
    };
    // Generate the package-module registry (`pkg_modules: [N]{ path, source }`),
    // each entry embedding its `.bp` source. The generated file lives in its own
    // module so its `@embedFile`s resolve against the package `.bp` anonymous
    // imports; `std_prelude` re-exports the table for compiler-core to consume.
    var pkg_table_src: []const u8 =
        "// Generated by build.zig — do not edit. The \"std\" package registry.\n" ++
        "pub const pkg_modules = [_]struct { path: []const u8, source: []const u8 }{\n";
    for (std_pkg_files) |f| {
        const name = f[0 .. f.len - ".bp".len];
        pkg_table_src = b.fmt(
            "{s}    .{{ .path = \"std/{s}\", .source = @embedFile(\"{s}\") }},\n",
            .{ pkg_table_src, name, f },
        );
    }
    pkg_table_src = b.fmt("{s}}};\n", .{pkg_table_src});

    const wf = b.addWriteFiles();
    const pkg_table_file = wf.add("std_pkg_modules.zig", pkg_table_src);
    const std_pkg = b.createModule(.{
        .root_source_file = pkg_table_file,
        .target = target,
    });
    for (std_pkg_files) |f| {
        std_pkg.addAnonymousImport(f, .{
            .root_source_file = b.path(b.fmt("libs/std/src/{s}", .{f})),
        });
    }
    std_prelude.addImport("std_pkg", std_pkg);

    // ── compiler-core (library) ───────────────────────────────────────────────

    const core_mod = b.addModule("botopink", .{
        .root_source_file = b.path("modules/compiler-core/src/root.zig"),
        .target = target,
        .imports = &.{
            .{ .name = "std_prelude", .module = std_prelude },
        },
    });

    // ── compiler-core tests ───────────────────────────────────────────────────

    const core_test_mod = b.addModule("botopink_tests", .{
        .root_source_file = b.path("modules/compiler-core/src/test_root.zig"),
        .target = target,
        .imports = &.{
            .{ .name = "std_prelude", .module = std_prelude },
        },
    });

    const test_filters = b.option([]const []const u8, "test-filter", "Only run tests matching filter") orelse &.{};
    const core_tests = b.addTest(.{
        .root_module = core_test_mod,
        .filters = test_filters,
    });

    const run_core_tests = b.addRunArtifact(core_tests);
    // Ensure snapshots are written inside modules/compiler-core/,
    // not at the workspace root.
    run_core_tests.setCwd(b.path("modules/compiler-core"));

    const test_step = b.step("test", "Run every test (compiler-core + language-server)");
    test_step.dependOn(&run_core_tests.step);

    // ── lib-agnostic gate (annotation-processors P0) ──────────────────────────
    // HARD RULE: the compiler core must name no specific NON-std library. Fail
    // the build if any framework name leaks into `modules/compiler-core/src`.
    // `std` is the one allowed exception (deliberately absent from the
    // alternation). Extend the pattern as frameworks are added. `grep` exits 1
    // when nothing matches, so `!` turns "clean" into success; a match → exit 0
    // → `!` → failure. This file lives outside the scanned tree, so it may name
    // the forbidden tokens. Runs as part of `zig build test`.
    const lib_agnostic_gate = b.addSystemCommand(&.{
        "sh",                                                             "-c",
        "! grep -riIE 'rakun|jhonstart|erika' modules/compiler-core/src",
    });
    lib_agnostic_gate.has_side_effects = true; // never cache — always re-scan
    test_step.dependOn(&lib_agnostic_gate.step);

    // ── language-server tests ─────────────────────────────────────────────────

    const lsp_test_mod = b.createModule(.{
        .root_source_file = b.path("modules/language-server/src/test_root.zig"),
        .target = target,
        .imports = &.{
            .{ .name = "botopink", .module = core_mod },
        },
    });

    const lsp_tests = b.addTest(.{ .root_module = lsp_test_mod, .filters = test_filters });
    const run_lsp_tests = b.addRunArtifact(lsp_tests);
    run_lsp_tests.setCwd(b.path("modules/language-server"));

    test_step.dependOn(&run_lsp_tests.step);

    // ── compiler-cli tests ────────────────────────────────────────────────────
    // Rooted at the CLI entry so every `test {}` reachable through its import
    // graph runs (scanner/resolver/libs source-loading logic).

    const cli_test_mod = b.createModule(.{
        .root_source_file = b.path("modules/compiler-cli/src/main.zig"),
        .target = target,
        .imports = &.{
            .{ .name = "botopink", .module = core_mod },
        },
    });

    const cli_tests = b.addTest(.{ .root_module = cli_test_mod, .filters = test_filters });
    const run_cli_tests = b.addRunArtifact(cli_tests);
    run_cli_tests.setCwd(b.path("modules/compiler-cli"));

    test_step.dependOn(&run_cli_tests.step);

    // ── compiler-cli (botopink executable) ────────────────────────────────────

    const cli_exe = b.addExecutable(.{
        .name = "botopink",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/compiler-cli/src/main.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "botopink", .module = core_mod },
            },
        }),
    });

    b.installArtifact(cli_exe);

    // ── language-server (botopink-lsp executable) ─────────────────────────────

    const lsp_exe = b.addExecutable(.{
        .name = "botopink-lsp",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/language-server/src/main.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "botopink", .module = core_mod },
            },
        }),
    });

    b.installArtifact(lsp_exe);

    // ── Run step ──────────────────────────────────────────────────────────────

    const run_cmd = b.addRunArtifact(cli_exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);

    const run_step = b.step("run", "Build and run the botopink CLI");
    run_step.dependOn(&run_cmd.step);
}
