#!/usr/bin/env bash
# status.sh — print a live progress rollup for a spec set (docs-refactor F4).
#
# Usage: scripts/status.sh <set>          e.g. scripts/status.sh v0.beta.2
#
# For every spec in tasks/<set>/specs/<slug>.md it derives (D3):
#   branch    task/<slug>          — exists? merged into the current branch?
#   worktree  .tasks/<slug>/       — present? TODO.md checkbox progress?
#   header    **Status** line of the spec (coarse, as-authored)
#
# Output is a markdown table on stdout — paste/redirect into
# tasks/<set>/status.md (keep that file's authored header notes).
# This script never writes files itself.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

set_name="${1:?usage: scripts/status.sh <set>  (e.g. v0.beta.2)}"
specs_dir="tasks/$set_name/specs"
[ -d "$specs_dir" ] || {
    echo "status.sh: no such set: $specs_dir" >&2
    exit 1
}

echo "# Task status — $set_name (generated)"
echo
echo "> Generated by \`scripts/status.sh $set_name\` on branch \`$(git branch --show-current)\`"
echo "> at commit \`$(git rev-parse --short HEAD)\`. Derived view — specs stay authored."
echo
echo "| Spec | Header status | Branch \`task/<slug>\` | Worktree \`.tasks/<slug>\` | TODO.md |"
echo "|---|---|---|---|---|"

for spec in "$specs_dir"/*.md; do
    slug=$(basename "$spec" .md)

    header=$(grep -m1 -oP '^\*\*Status\*\*: *\K.*' "$spec" || echo "—")

    branch="task/$slug"
    if git show-ref --quiet "refs/heads/$branch"; then
        if git merge-base --is-ancestor "$branch" HEAD 2>/dev/null; then
            branch_state="merged"
        else
            branch_state="open ($(git rev-parse --short "$branch"))"
        fi
    else
        branch_state="—"
    fi

    todo=".tasks/$slug/TODO.md"
    if [ -f "$todo" ]; then
        wt_state="present"
        done_n=$(grep -c '^\s*- \[x\]' "$todo" || true)
        open_n=$(grep -c '^\s*- \[ \]' "$todo" || true)
        todo_state="${done_n}/$((done_n + open_n)) done"
    elif [ -d ".tasks/$slug" ]; then
        wt_state="present (no TODO.md)"
        todo_state="—"
    else
        wt_state="—"
        todo_state="—"
    fi

    echo "| [$slug](specs/$slug.md) | $header | $branch_state | $wt_state | $todo_state |"
done
